# Changes here will be overwritten by Copier
_commit: 2024.09.24
_src_path: gh:zenml-io/template-starter
email: jclyde_jutsu_090@yahoo.com
full_name: JCA
open_source_license: mit
project_name: ZenML Starter 01
version: 0.1.0
